language: c

matrix:
  include:
    # Test using python 3.8 on Linux and OSX
    - os: linux
      env: PYTHON_VERSION=3.8
    - os: osx
      env: PYTHON_VERSION=3.8
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local

addons:
  apt:
    packages:
    - gfortran
  homebrew:
    packages:
    - wget
    update: true

install:
  # Download and install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
    else
      export OS="Linux";
    fi

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r

  # Configure conda testing environment
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda

  # - conda create -q -n test-environment -c anaconda
  #      numpy
  # - conda install -n test-environment -c conda-forge
  - conda create -q -n test-environment
        python=$PYTHON_VERSION
        defaults::numpy
        fftw>=3.3.8
        liblapack>=3.8
        openblas
        gmt
        scipy
        matplotlib=3.3.*
        astropy
        xarray
        requests
        cartopy
        pygmt
        pooch
        tqdm
        jupyter
        palettable
        pypandoc
  - conda activate test-environment

  # Conda info for debugging
  - conda list -n test-environment
  - conda info -a
  - conda config --show-sources

  # Install pyshtools
  - pip install --no-deps .

script:
  - python examples/notebooks/test_notebooks.py
  - export MPLBACKEND=Agg
  - make -C examples/python -f Makefile no-timing
  - mkdir empty && cd empty
  - python -c "import pyshtools"

notifications:
    email: false
